SELECT DISTINCT tm.FCONTABLE FECHA,tm.STRANSACCION,tp.IDENTIFICACION,tp.NOMBRELEGAL NOMBRE,tc.CCUENTA OPERACION,
(CASE 
  WHEN (SELECT COUNT(SALDOMONEDACUENTA) FROM TSALDOS WHERE CCUENTA=tm.CCUENTA AND CATEGORIA=tm.CATEGORIA AND FCONTABLEDESDE>=tm.FCONTABLE AND SALDOMONEDAOFICIAL=0 AND CUSUARIO<>'1')>0
    THEN 'COBRADO'
  WHEN (SELECT VALORMONEDAOFICIAL FROM TMOVIMIENTOS tmov 
    WHERE tmov.ccuenta=tm.ccuenta and tmov.categoria=tm.categoria and tmov.fcontable>=tm.fcontable and tmov.cusuario='BATCH' 
    AND tmov.valormonedaoficial=tm.valormonedaoficial and tmov.cgrupobalance=1 
    AND (SELECT COUNT(CCUENTA) FROM TMOVIMIENTOS tmov2 WHERE tmov2.valormonedaoficial=tm.valormonedaoficial and tmov2.cgrupobalance=2 and tmov2.Freal>tm.Freal and tmov2.ccuenta=tm.ccuenta)=0
    )IS NOT NULL      
    THEN 'COBRADO'
  ELSE 'NO COBRADO'END ) ESTADO,
tof2.COFICINA,tof2.nombre AGENCIA,tcl.DESCRIPCION SEGMENTO,tst.DESCRIPCION ESTATUS,tm.ctransaccion_origen, tcat.DESCRIPCION TIPO, tm.VALORMONEDAOFICIAL VALOR,TM.DEBITOCREDITO,tm.Cusuario,tm.Numerocomprobante
FROM TMOVIMIENTOS tm,  TCUENTA tc,TPERSONA tp, TOFICINAS tof2, TCATEGORIAS tcat, TCLASIFICACIONCONTABLE tcl, TESTATUSCUENTA tst
WHERE tm.CCUENTA=tc.CCUENTA 
AND  tm.CGRUPOBALANCE=2
AND tcat.CGRUPOBALANCE=2
AND tc.CPERSONA_CLIENTE=TP.CPERSONA 
AND tof2.coficina=tc.coficina
AND tm.CUSUARIO<>'1'
AND tm.REVERSO=0
AND tof2.FHASTA=fncfhasta
AND tc.FHASTA=fncfhasta 
AND tcl.FHASTA=fncfhasta 
AND tst.FHASTA=fncfhasta 
AND tp.FHASTA=fncfhasta 
AND tcat.FHASTA=fncfhasta
AND tm.CATEGORIA IN ('CXC44','CXC36','CXC40','CXC42','CXC39','CXC49','CXC45','CXC38','CXC41','CXC47','CXC48','CXC5') 
AND (SELECT CCUENTA FROM TMOVIMIENTOS 
WHERE CCUENTA=tm.CCUENTA 
AND CATEGORIA=tm.CATEGORIA
 AND CGRUPOBALANCE=tm.Cgrupobalance 
AND VALORMONEDAOFICIAL=tm.VALORMONEDAOFICIAL 
AND REVERSO=1 AND FCONTABLE=tm.FCONTABLE) is null
AND tm.CATEGORIA=tcat.CATEGORIA 
AND tm.CTRANSACCION_ORIGEN IN ('2004','3073','3026')
AND tm.CCLASIFICACIONCONTABLE=tcl.CCLASIFICACIONCONTABLE
 AND tcl.CSUBSISTEMA IN ('06') AND tm.CSUBSISTEMA IN ('06') 
--AND tm.FCONTABLE<SYSDATE 
--and tm.fcontable = to_date('16-09-2022','dd-mm-yyyy')
and tm.ccuenta='642000003337-1'
and tc.CESTATUSCUENTA=tst.CESTATUSCUENTA and tc.csubsistema=tst.csubsistema
ORDER BY tcat.descripcion,tm.FCONTABLE, tp.Nombrelegal
