SELECT
TT.COFICINA_CUENTA,
       TT.CMONEDA_CUENTA,
        TT.CGRUPOPRODUCTO,
       TT.CPRODUCTO,
       TT.CSUCURSAL_CUENTA,
       (SELECT distinct NOMBRELEGAL
            FROM TCUENTA A, TPERSONA B
            WHERE A.CCUENTA = TT.CCUENTA
            AND A.CPERSONA_CLIENTE = B.CPERSONA
            AND B.FHASTA=fncfhasta
            AND A.FHASTA=fncfhasta
    ) NOMBRE_CLIENTE,
    (select nombrelegal from tpersona where cpersona = (select cpersona from tusuarios where cusuario = '718'and fhasta = fncfhasta) and fhasta = fncfhasta)USUARIO,
(select NOMBRELEGAL from tpersona where CPERSONA='2' and FHASTA=fncfhasta)NOMBRELEGAL1,
TT.CCUENTA, TT.CATEGORIA, TT.CCANAL, TT.CODIGOCONTABLE, TT.FREAL, TT.FCONTABLE, TT.CUSUARIO
,(SELECT TP.NOMBRELEGAL FROM TUSUARIOS TU JOIN TPERSONA TP USING (FHASTA,CPERSONA) WHERE TT.CUSUARIO=TU.CUSUARIO GROUP BY  TP.NOMBRELEGAL)NOMBREUSUARIO,
(
SELECT DISTINCT CASE WHEN TU.CUSUARIO='BATCH' THEN 'MATRIZ LOJA' 
      ELSE TS.NOMBRE END AGENCIANOMBRE
FROM tpersona tp 
LEFT JOIN tusuarios tu ON tu.cpersona =tp.cpersona
LEFT JOIN tcompaniausuarios  tcu ON tcu.cusuario=tu.cusuario
LEFT JOIN tsucursales ts ON ts.csucursal=tcu.csucursal
WHERE TU.CUSUARIO=TT.CUSUARIO
AND ROWNUM =1
)AGENCIAUSUARIO,
(select nombrelegal from tpersona where cpersona = (select cpersona from tusuarios where cusuario = '718' and fhasta = fncfhasta) and fhasta = fncfhasta)USUARIO,
(select NOMBRELEGAL from tpersona where CPERSONA='2' and FHASTA=fncfhasta)NOMBRELEGAL1,
TT.CCUENTA, TT.CATEGORIA, TT.CCANAL, TT.CODIGOCONTABLE, TT.FREAL, TT.FCONTABLE, TT.CUSUARIO, TT.CSUBSISTEMA_TRANSACCION, TT.CTRANSACCION,
(
select COALESCE(SUMACOMPONENTES,'0') from TSUBSISTEMATRANSACCIONESID TSI
where
TSI.CSUBSISTEMA = TT.CSUBSISTEMA_TRANSACCION
and TSI.CTRANSACCION = TT.CTRANSACCION
and TSI.VERSIONTRANSACCION = TT.VERSIONTRANSACCION
) SUMACOMPONENTES,
--TT.CCANAL||'-'||case when TT.REVERSO = '1' then 'REVERSO' else '' end ||COALESCE(TD.DESCRIPCION,TS.DESCRIPCION)DESCRIPCION,
TT.DETALLE,
CASE WHEN TT.DEBITOCREDITO = 'D' THEN TT.VALORMONEDACUENTA ELSE null END VALORDEBITOCUENTA,
CASE WHEN TT.DEBITOCREDITO = 'C' THEN TT.VALORMONEDACUENTA ELSE null END VALORCREDITOCUENTA,
TT.NUMERODOCUMENTO,ds.dss
from
(select unique tm.CCANAL ||'-'||case when tm.REVERSO = '1' then 'REVERSO' else '' end ||COALESCE(Tst.DESCRIPCION,ttr.DESCRIPCION)dss 
from TTRANSACCIONRUBROS ttr,TSUBSISTEMATRANSACCIONES tst,tmovimientos tm 
where ttr.csubsistema=tm.csubsistema_transaccion  
 and tm.csubsistema_transaccion=ttr.ctransaccion and ttr.fhasta=fncfhasta and tst.fhasta=fncfhasta
 and tm.versiontransaccion=ttr.versiontransaccion and tm.versiontransaccion=tst.versiontransaccion
 and tm.rubro=ttr.rubro 
 )ds,
TMOVIMIENTOS TT, TSUBSISTEMATRANSACCIONES TS, TTRANSACCIONRUBROS TD, TTRANSACCIONRUBROSDEFINICION TC
where
TT.CSUBSISTEMA_TRANSACCION = TS.CSUBSISTEMA
and TT.CTRANSACCION = TS.CTRANSACCION
and TT.VERSIONTRANSACCION = TS.VERSIONTRANSACCION
and TS.CIDIOMA = 'ES'
and TS.FHASTA = fncfhasta
and TT.CSUBSISTEMA_TRANSACCION = TC.CSUBSISTEMA
and TT.CTRANSACCION = TC.CTRANSACCION
and TT.VERSIONTRANSACCION = TC.VERSIONTRANSACCION
and TT.RUBRO = TC.RUBRO
and ( TC.OCULTAESTADODECUENTA = '0' or TC.OCULTAESTADODECUENTA is null)
and TT.CSUBSISTEMA_TRANSACCION = TD.CSUBSISTEMA
and TT.CTRANSACCION = TD.CTRANSACCION
and TT.VERSIONTRANSACCION = TD.VERSIONTRANSACCION
and TT.RUBRO = TD.RUBRO
and TD.FHASTA = fncfhasta
and TT.CTIPOSALDOCATEGORIA = 'SAL'
and TT.CATEGORIA not in ('INTERS')
and TT.VALORMONEDACUENTA > 0
and TT.FCONTAB LE = to_Date('30-09-2022','dd-mm-yyyy')
and '&DESCRIPCION' = ANY (SELECT case when)
